name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Install Dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run checks
        run: |
          source .venv/bin/activate
          django-admin startproject core
          mv rest_wind core
          echo "INSTALLED_APPS += ['rest_wind', 'rest_framework']" >> core/settings.py
          python core/manage.py check
